
package menuutama;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;

/**
 *
 * @author Siti Mawaddah
 */
public class DataLaptop extends javax.swing.JPanel {
    // koneksi mysql
    private Connection conn = new Koneksi().connect();
    private DialogTambahData dialog = new DialogTambahData(null, true);
    public DefaultTableModel tabmode;
    private String noId;

    /**
     * Creates new form NewJPanel
     */
    public DataLaptop() {
        initComponents();
        updateDataTabel();
    }

    /**
     * mendapatkan Data Tabel dari database
     */
    protected void updateDataTabel() {
        Object[] Baris = {
                "ID Laptop",
                "Nama Laptop",
                "Merk",
                "Harga",
                "Processor",
                "RAM",
                "Storage",
                "Battery Life",
                "Performa",
                "Kategori Harga",
                "Kategori Penyimpanan",
                "Kategori Daya Tahan",
                "Kategori RAM"
        };

        tabmode = new DefaultTableModel(null, Baris);
        tabelDataLaptop.setModel(tabmode);

        String sql = "SELECT * FROM data_laptop ORDER BY id_laptop";

        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String a = hasil.getString("id_laptop");
                String b = hasil.getString("nama_laptop");
                String c = hasil.getString("merk");
                String d = hasil.getString("harga");
                String e = hasil.getString("processor");
                String f = hasil.getString("ram");
                String g = hasil.getString("storage");
                String h = hasil.getString("battery_life");
                String i = hasil.getString("performa");
                String j = hasil.getString("kategori_harga");
                String k = hasil.getString("kategori_penyimpanan");
                String l = hasil.getString("kategori_daya_tahan");
                String m = hasil.getString("kategori_ram");

                String[] data = { a, b, c, d, e, f, g, h, i, j, k, l, m };
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * Mendapatkan Data dari Tabel
     */
    private void getDataTabel() {
        int bar = tabelDataLaptop.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        String i = tabmode.getValueAt(bar, 8).toString();
        String j = tabmode.getValueAt(bar, 9).toString();
        String k = tabmode.getValueAt(bar, 10).toString();
        String l = tabmode.getValueAt(bar, 11).toString();
        String m = tabmode.getValueAt(bar, 12).toString();

        noId = a;
        dialog.setDataTabel(a, b, c, d, e, f, g, h, i, j, k, l, m);
    }

    protected void hapusDataLaptop() {
        if (noId != null) {
            int ok = JOptionPane.showConfirmDialog(null, "hapus", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
            if (ok == 0) {
                String sql = "DELETE FROM data_laptop WHERE id_laptop='" + noId + "'";
                try {
                    PreparedStatement stat = conn.prepareStatement(sql);
                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil diHapus ");
                    updateDataTabel();
                    noId = null;
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Data Gagal diHapus " + e);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus! ");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataLaptop = new javax.swing.JTable();
        tombolTambah = new javax.swing.JButton();
        tombolEdit = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();
        catatan = new javax.swing.JLabel();

        setBackground(new java.awt.Color(178, 176, 232));

        judul.setBackground(new java.awt.Color(26, 42, 128));
        judul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        judul.setForeground(new java.awt.Color(204, 255, 255));
        judul.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        judul.setText("  Data Laptop");
        judul.setOpaque(true);

        Panel.setBackground(new java.awt.Color(178, 176, 232));

        tabelDataLaptop.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tabelDataLaptop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Laptop", "Nama Laptop", "Merk", "Bobot Laptop", "Tahun Produksi", "Performa", "Harga", "Penyimpanan", "Ketahanan Baterai", "Ram"
            }
        ));
        tabelDataLaptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataLaptopMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDataLaptop);

        tombolTambah.setBackground(new java.awt.Color(26, 42, 128));
        tombolTambah.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tombolTambah.setForeground(new java.awt.Color(204, 255, 255));
        tombolTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon Tambah Small.png"))); // NOI18N
        tombolTambah.setText("TAMBAH");
        tombolTambah.setBorder(null);
        tombolTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambahActionPerformed(evt);
            }
        });

        tombolEdit.setBackground(new java.awt.Color(26, 42, 128));
        tombolEdit.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tombolEdit.setForeground(new java.awt.Color(204, 255, 255));
        tombolEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon Ubah Small.png"))); // NOI18N
        tombolEdit.setText("UBAH");
        tombolEdit.setBorder(null);
        tombolEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolEditActionPerformed(evt);
            }
        });

        tombolHapus.setBackground(new java.awt.Color(26, 42, 128));
        tombolHapus.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tombolHapus.setForeground(new java.awt.Color(204, 255, 255));
        tombolHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon Hapus Small.png"))); // NOI18N
        tombolHapus.setText("HAPUS");
        tombolHapus.setBorder(null);
        tombolHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusActionPerformed(evt);
            }
        });

        catatan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        catatan.setText("Catatan : Edit/Hapus data laptop, klik data pada tabel terlebih dahulu");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tombolEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tombolHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(451, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(catatan, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(398, Short.MAX_VALUE)))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLayout.createSequentialGroup()
                    .addGap(265, 265, 265)
                    .addComponent(catatan)
                    .addGap(0, 149, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tombolHapusActionPerformed
        // TODO add your handling code here:
        hapusDataLaptop();
    }// GEN-LAST:event_tombolHapusActionPerformed

    private void tombolEditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tombolEditActionPerformed
        // TODO add your handling code here:
        if (noId != null) {
            dialog.setVisible(true);
            updateDataTabel();
            noId = null;
        } else {
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin diubah!");
        }
    }// GEN-LAST:event_tombolEditActionPerformed

    private void tombolTambahActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tombolTambahActionPerformed
        // TODO add your handling code here:
        dialog.kosong();
        dialog.setVisible(true);
        updateDataTabel();
        noId = null;
    }// GEN-LAST:event_tombolTambahActionPerformed

    private void tabelDataLaptopMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tabelDataLaptopMouseClicked
        // TODO add your handling code here:
        getDataTabel();
    }// GEN-LAST:event_tabelDataLaptopMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel catatan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JTable tabelDataLaptop;
    private javax.swing.JButton tombolEdit;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolTambah;
    // End of variables declaration//GEN-END:variables
}
